Document: render-expired
Title: Debian render-expired Manual
Author: <insert document author here>
Abstract: This manual describes what render-expired is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/render-expired/render-expired.sgml.gz

Format: postscript
Files: /usr/share/doc/render-expired/render-expired.ps.gz

Format: text
Files: /usr/share/doc/render-expired/render-expired.text.gz

Format: HTML
Index: /usr/share/doc/render-expired/html/index.html
Files: /usr/share/doc/render-expired/html/*.html
